### ISSUE TITLE
addwindow doesn't work for totp

### ISSUE THREAD

**Issue by samsondav** [yuce/pot#18]
As per title.  addwindow does not appear to work correctly, if set to anything other than 0 it causes all tokens to be invalid.

**Comment by samsondav** [comment]
I was confused by this because addwindow in the Python lib works differently to addwindow here.

Closing.

**Comment by samsondav** [comment]
Re-opening because I still haven't managed to solve my problem. Here is what I want to achieve:

+/-30s leniency on token checking.

I thought that specifying `window: 1` would do this, but it doesn't. Instead I still get failures if my timestamp is slightly too early.

**Comment by nalundgaard** [comment]
@samphilipd Looks like you're right! It looks like there was, indeed, an off-by-one error on the logic of `check_candidate`. I've proposed #20, which fixes that does [much the same as you did](https://github.com/yuce/pot/pull/19/files#diff-0e6ce6f4ecd5cd4301152a0c6c7079bcR125) in https://github.com/yuce/pot/pull/19 without the problem of breaking the `window/addwindow` option, and adding some tests around this case.
