### ISSUE TITLE
[Elixir]: function :crypto.hmac/3 is undefined or private, use crypto:mac/4 instead

### ISSUE THREAD

**Issue by alma3lol** [yuce/pot#36]
An error keeps showing when using the library. I traced it down to `OTP_RELEASE` not being defined.  

Is there something I'm not doing to define `OTP_RELEASE`?  

![image](https://user-images.githubusercontent.com/46169717/227786008-13742f40-a314-4d27-9182-8bbccf4c4c5c.png)

elixir --version:
```
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)
```

**Comment by ariesclark** [comment]
``src/pot.erl:58:14: Warning: crypto:hmac/3 is removed; use crypto:mac/4 instead``

**Comment by yuce** [comment]
@alma3lol i've tried the following on Elixir 14.4 compiled with OTP 25 (Ubuntu 22.04) in a mix project, and don't get any errors:
```
iex(4)> secret = "MFRGGZDFMZTWQ2LK" 
"MFRGGZDFMZTWQ2LK"
iex(5)> token = :pot.totp(secret)
"237045"
```
Could you try again in a new VM or container to rule out any problems in your setup?

**Comment by alma3lol** [comment]
> Could you try again in a new VM or container to rule out any problems in your setup?

I actually have two machines with the same setup and the problem exists on both. 
My setup is Arcolinux (arch based destro). 
Clean install -> `yay -S erlang elixir`

**Comment by HammamSamara** [comment]
I am having the same issue. `:crypto.hmac/3` is not available in OTP 25.

Crypto related libs ([plug-crypto](https://github.com/elixir-plug/plug_crypto/blob/6ba8fd42a68351459fe6c769ca04aea6022a5cd1/lib/plug/crypto/key_generator.ex#L96) for example) are using a fallback check to mitigate this error.

**Comment by yuce** [comment]
I tried this with clean install of Archlinux and it seems to work fine. Here are the steps I followed:
1. Create an Archlinux container using LXC: `lxc launch images:archlinux/current arch`
2. Login to the container: `lxc exec arch -- sudo -i -u root`
3. Install Elixir: `pacman -S elixir`
4. Create a new project: `mix new pot1`
5. Updated `mix.exs` with `{:pot, "~> 1.0"}`
6. `iex -S mix`
7. And then tried the lines in my previous message:

```
[root@arch pot1]# iex -S mix
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> secret = "MFRGGZDFMZTWQ2LK" 
"MFRGGZDFMZTWQ2LK"
iex(2)> token = :pot.totp(secret)
"304398"
```

Is it possible that there's something wrong with Arcolinux's Erlang package?

**Comment by Ishan-co** [comment]
I have the same problem on mac:
`Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace]`
any fixes?

**Comment by xn** [comment]
@yuce please take a look here: 
![Screenshot 2023-11-19 at 11 53 35 PM](https://github.com/yuce/pot/assets/2286/ab7706b7-4d60-48d5-8307-5e4fd6d71cd3)

https://www.erlang.org/doc/general_info/deprecations#crypto-old-api
https://www.erlang.org/doc/apps/crypto/new_api#the-new-api

I am currently getting this error using `:pot.hotp/2` and `0.10.2`

**Comment by xn** [comment]
Also there are compile warnings:
<img width="635" alt="Screenshot 2023-11-19 at 11 59 34 PM" src="https://github.com/yuce/pot/assets/2286/1faa44cb-1361-4609-b7f7-91777f1e1216">

**Comment by xn** [comment]
Ok, sorry, @yuce. I see that you dealt with the new API in 2021. I'm looking to see why my env is not registering the correct version of OTP. I'll post back later for anyone else who runs into this.

**Comment by yuce** [comment]
The most recent version of Pot should not have this issue.
Please feel free to reopen the issue if necessary.
