### ISSUE TITLE
is it possible to have 4 digit token, not 6

### ISSUE THREAD

**Issue by a9a4k** [yuce/pot#4]
So basically I want to generate 4 digit code instead of 6 and also want to control expiration

**Comment by yuce** [comment]
That is not possible with this library which implements HOTP algorithm. 6 digits is the minimum. See: https://en.wikipedia.org/wiki/HMAC-based_One-time_Password_Algorithm

**Comment by a9a4k** [comment]
Thanks for the link. I guess will have to stick with 6. 
I have one more question: is it possible to control expiration time? i.e. 30 minutes, 1 hour. Currently it seems like the code expires in a minute or even less

**Comment by yuce** [comment]
Sorry, I was wrong on the token length. You can specify the token length by passing e.g., `{token_length, Length}` in a proplist, like: `pot:totp(Secret, [{token_length, 4}]).`. And token expiration with `{interval_length, Seconds}`, .e.g: `pot:totp(Secret, [{token_length, 4}, {interval_length, 3600}]).`. But specifying these settings may create tokens incompatible with Google Authenticator, in case you care.

**Comment by a9a4k** [comment]
Oh thanks! Thats what I was looking for
