### ISSUE TITLE
Base encoded handling in Pot

### ISSUE THREAD

**Issue by dabaer** [yuce/pot#6]
I'm having an issue with Pot decoding the TOTP secret with padding. The Google authenticator does not work with base encoded secrets that are padded, so if an encoded string happens to be padded, the authenticator will not accept it. The issue with pot is that it decodes the secret _with_ padding, and throws an error if the encoded string would normally have padding if it does not.

Basically, if I `Base.encode32(secret, padding: false)` in elixir with a string that would include padding if i used `padding: true` pot:totp will throw an error such as:

```
** (ArgumentError) argument error
    (crypto) :crypto.hmac_nif(:sha, <<...>>, <<...>>)
    (crypto) crypto.erl:766: :crypto.hmac/6
             /path/deps/pot/src/pot.erl:60: :pot.hotp/3
```

But again, the authenticator doesn't work with padded encoded strings.

EDIT: Yes, I am URL encoding the secret. The result is also the same regardless if the Base padding is encoded as %3D or as =.

Edit 2: The google auth problem is more of a clarification, as I can't find anything in the documentation regarding the paddedness of the secret used on the authenticator.

Regards,
Jadenn

**Comment by yuce** [comment]
Thanks for the bug report. Would it be possible for you to attach a test case ? It would be even awesomer In case you can send a pull request to fix the issue. Otherwise it may take me some time to get back to this.

**Comment by yuce** [comment]
Closing this issue. We can reopen it if anyone comes with a test case and/or PR.
